// <auto-generated />
using System;
using Main_Bot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main_Bot.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220108184015_somenewshit")]
    partial class somenewshit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GuildUser", b =>
                {
                    b.Property<int>("guildskey")
                        .HasColumnType("int");

                    b.Property<int>("userskey")
                        .HasColumnType("int");

                    b.HasKey("guildskey", "userskey");

                    b.HasIndex("userskey");

                    b.ToTable("GuildUser");
                });

            modelBuilder.Entity("Main_Bot.Models.Guild", b =>
                {
                    b.Property<int>("key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("guildSettingskey")
                        .HasColumnType("int");

                    b.Property<ulong>("id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("key");

                    b.HasIndex("guildSettingskey");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Main_Bot.Models.GuildSettings", b =>
                {
                    b.Property<int>("key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong?>("administratorRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("hiddenRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("moderatorRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("muteRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("rainbowRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("verifyRoleId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("key");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("Main_Bot.Models.Logs.ErrorLog", b =>
                {
                    b.Property<int>("key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("errorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("location")
                        .HasColumnType("longtext");

                    b.Property<string>("message")
                        .HasColumnType("longtext");

                    b.HasKey("key");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("Main_Bot.Models.User", b =>
                {
                    b.Property<int>("key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("accessToken")
                        .HasColumnType("longtext");

                    b.Property<ulong>("id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("refreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("key");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GuildUser", b =>
                {
                    b.HasOne("Main_Bot.Models.Guild", null)
                        .WithMany()
                        .HasForeignKey("guildskey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main_Bot.Models.User", null)
                        .WithMany()
                        .HasForeignKey("userskey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main_Bot.Models.Guild", b =>
                {
                    b.HasOne("Main_Bot.Models.GuildSettings", "guildSettings")
                        .WithMany()
                        .HasForeignKey("guildSettingskey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("guildSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
