//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyJhbGciOiJSU0EtT0FFUC01MTIiLCJ0eXAiOiJKV1QgQ3VzdG9tIiwiZW5jIjoiQTI1NkdDTSJ9.B81gGADL6oWF3qnPY4CWZbJ5dgMDSYD7c4x5nPNmhOxyfwtyNvg3H6UZkQxW6Mw4YWnAwKi_Qw3Qc_HQgYr6CZGzJ-wqt1g5MO9E4-KQcrByFTjkiZdUbXKqYe-BuDfLjxWoApyHnTWEdSpWEAigodaKzeeOCjFJ82tj8WPmsEt7Cd3N0qgI7oJMX3otmSJIskgW5zTy9m-Csrx8xhBRFUsTIkCKganR3Xg1S6vtyMjgRkwo3HPPXteccuVQjEs49KIwj4a2914U6gHmgd8JTFrye2Z8uY-QVnuEyhgcjkOUIA-_0ExQgrE968avJba3RYksUDy5gL0ltbQL7bF9prLhGGe30BoMDt3l8awsAMzhcat_EQ2TRk5IZN8vM5L6wMsKK6eZmsXv6lV15OtemnHaY5qelCP4_J6y1VdBOrw.b6Hl4_t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string APIToken {
            get {
                return ResourceManager.GetString("APIToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sNCa7dyszVdWqW9W4nKfNge9VvTd3gn2.
        /// </summary>
        internal static string MySql_Pass {
            get {
                return ResourceManager.GetString("MySql_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTcwNzU3MTY3MDEzNTg5MDMz.GK-wQ2.j8gEEjUDrnpVS0t48NOjQhQFJ32hJZNcKl1aSc.
        /// </summary>
        internal static string TestToken {
            get {
                return ResourceManager.GetString("TestToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTcwNzU3Mzc3MjMyMTA5NjM4.YnAmQg.rJ9Z23WGjedy_koRxciWP9xJIPk.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
    }
}
